### ISSUE TITLE
Question about the "file" argument when running ResourceConverter.sh

### ISSUE THREAD

**Issue by Jern97** [PMheart/CPUFriend#2]
The instructions say: 
"The variable file should be a complete plist from /System/Library/Extensions/IOPlatformPluginFamily.kext/Contents/PlugIns/X86PlatformPlugin.kext/Contents/Resources with certain modifications"

I don't really know what do to here. I can see a bunch of plist files in that location but have no idea which one should I use and what modifications I have to do? 

I searched online but can't seem to find another guide.

Thanks!

**Comment by PMheart** [comment]
Hi,

> I don't really know what do to here. I can see a bunch of plist files in that location but have no idea which one should I use and what modifications I have to do?
In this case, just forget this repo, it's simply not for you.
You are going to set it up only when you know why should you patch something.

Best Regards,
PMheart

**Comment by PMheart** [comment]
Well, still somewhat curious? (This)[https://github.com/Piker-Alpha/freqVectorsEdit.sh] might be a door to enter.

**Comment by Jern97** [comment]
Yes i know i'm still a noob, but I managed to get mac OS working on my laptop using this repo:
https://github.com/the-darkvoid/XPS9360-macOS

However I don't have the same CPU (i7 7500U) as he has so I need custom CPUFriend kexts to get the power management right.
Thanks for the link, I now know which plist I need. I'll do some more research on the modifications that are needed.

**Comment by PMheart** [comment]
Well, now that the new MBP with CoffeeLake has been released (MBP15,1 and MBP15,2), which means that there has been native support for CFL.
Admittedly the docs/guides regarding FrequencyVectors that CPUFriend mainly deals with are very deficient, thus I do not think one should ever attempt to modify anything before things get clear.
In a word, you are supposed to set your SMBIOS to either MBP15,1 or MBP15,2 WITHOUT CPUFriend and see how everything goes. I guess that that will basically satisfy you since certain aspects defined in FrequencyVectors could be dynamically adjusted by the whole XCPM mechanism more or less. If that does not fit you well at all, then start seeking for something, plus I could somehow help if I have some time, which is hard to find...
Feel free to contact me, with the email as shown on [my blog](https://pmheart.site). :)

Issue reopened to keep tracking the progress.

**Comment by PMheart** [comment]
OK, as for KBL set SMBIOS to MBP14,1, MBP14,2, MBP14,3 or MB10,1.

Yup, it surely is working. In addition I made some comparisons and I found out that only the minimum frequency has been modified, which just benefits nothing. (The minimum frequency is 1.3GHz by default as set in the origin file, note that lowering it neither saves your battery life nor provide a better performance when idling)

So I don't think that there will be any need for you to modify X86PlatformPlugin, just delete CPUFriend.
Furthermore, the major reason why I wrote this kext was for my desktop with SMBIOS MP6,1, which does not contain an appropriate set of FrequencyVectors and thus has to be added manually... This was obviously totally another story...

**Comment by Jern97** [comment]
Yes I'm using SMBIOS MPB14,1. 

So it's using the same voltage on 0.5GHz as on 1.3GHz? Could that be the reason why my battery life on macOS is slightly worse than on Windows? I think the chip can clock lower in Windows.

**Comment by PMheart** [comment]
Regarding voltage, unfortunately I am not very sure, you may make comparisons by yourself.
I do not really think so, maybe that's due to differences of power management between macOS and Windows? Well, since I do not have a laptop hack, I cannot say anything...

**Comment by PMheart** [comment]
No news here? Issue closed.
