### ISSUE TITLE
New CPUFriend v1.1.5 set the Frequency Limit for my Intel I7-7500U to 1,3 GHz

### ISSUE THREAD

**Issue by anonymous-writer** [PMheart/CPUFriend#4]
Hello developer,
Thanks first to your work. I'm always excited about your work.

With the new CPU Friend I get the problem that the frequency limit was 1,3 GHz.
Installing v1.1.4 frequency limit goes down to 0,8 GHz.

Can someone help what is causing this problem? SSDT.aml I am use for both versions the same.
[ssdt.aml.zip](https://github.com/PMheart/CPUFriend/files/2364067/ssdt.aml.zip)

**Comment by PMheart** [comment]
Hi.

Could you please provide a reasonably complete log by using both Debug Lilu and Debug CPUFriend 1.1.5?

**Comment by PMheart** [comment]
I saw no point why you were unable to boot with Debug Lilu. Is it due to the extremely slow speed? If so, then it's expected because of `liludelay=1000`, which creates a one-second delay for you to see and record everything clearly. Simply do a video record with your phone in the meanwhile.

Unfortunately it's not very useful to trace the bug only with Debug CPUFriend.

Let me tag @vit9696 to participate in the issue, who may give you further help. :)
Thanks @vit9696 in advance.

**Comment by vit9696** [comment]
Should be fixed now. Please report.

**Comment by anonymous-writer** [comment]
The problem is fixed. Thank you for the outstanding help. 

![screenshot_2018-09-09 19 00 38_1aqodz](https://user-images.githubusercontent.com/35840715/45266903-0006ae80-b463-11e8-8ede-69e13cf8516f.jpg)
